# Assignment 4

# Numpy

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [1]:
#1
#Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    a=numpy.array(arr,float)
    return a[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#2
#shape and reshape
import numpy

n=list(map(int,input().split()))
print(numpy.reshape(n,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#3
#Transpose and flatten
import numpy as np
a,b=map(int,input().split())
l=[]
for i in range(a):
    j=list(map(int,input().split()))
    l.append(j)
arr=np.array(l)
print(arr.T)
print(arr.flatten())



2 2
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
#4
#COncatenate
import numpy as np
n,m,p=map(int,input().split())
lis=[]
for i in range(n+m):
    inp=input().split()
    lis.append(inp)
print(np.array(lis,int))

In [4]:
#5
#Zeros and one
import numpy 
nums = tuple(map(int, input().split())) #we use tuple because as per numpy docs zero and one are supported in tuplr
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [2]:
#6
#eye and identity
import numpy as np
n,m=list(map(int,input().split()))
np.set_printoptions(legacy='1.13')
print(np.eye(n,m))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [2]:
#7
#Array mathematics
import numpy as np
i, j = map(int, input().split())
a = np.array([list(map(int, input().split())) for i in range(i)], int)
b = np.array([list(map(int, input().split())) for i in range(i)], int)
print(np.add(a,b), np.subtract(a,b), np.multiply(a,b,), np.floor_divide(a,b), np.mod(a,b), np.power(a,b), sep = "\n")


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [3]:
#8
#floor ceil and Rint
import numpy as np

np.set_printoptions(legacy='1.13')
n=np.array(input().split(' '),float)
print(np.floor(n))
print(np.ceil(n))
print(np.rint(n))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [6]:
#9
#sum and product
import numpy as np
n,m=list(map(int,input().split()))
a=np.array([input().split() for i in range(n)],int)
ad=np.sum(a,axis=0)
print(np.prod(ad))


2 2
1 2
3 4
24


In [7]:
#10
#mean,var,std
n,m=list(map(int,input().split()))
a=np.array([input().split() for i in range(n)],int)
print(np.mean(a,axis=1))
print(np.var(a,axis=0))
print(np.std(a))

2 2
1 2 
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [8]:
#11
#Dot and cross
import numpy as np
n=int(input())
a=np.array([input().split() for i in range(n)],int)
b=np.array([input().split() for i in range(n)],int)
print(np.dot(a,b))

2
1 2 
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [2]:
#12
#min max
import numpy as np
n,m=map(int,input().split())
a=np.array([input().split() for i in range(n)],int)
b=np.min(a,axis=1)
print(np.max(b))


4 2
2 5
3 7
1 3
4 0
3


In [1]:
#13
#polynomial
import numpy as np
p=list(map(float,input().split()))
x=int(input())
ar=np.array(p)
print(np.polyval(ar,x))


1.1 2 3
0
3.0


In [4]:
#14
#Inner and outer
import numpy as np
a=list(map(int,input().split()))
b=list(map(int,input().split()))
arr=np.array(a)
arr1=np.array(b)
print(np.inner(arr,arr1))
print(np.outer(arr,arr1))



0 1
2 3
3
[[0 0]
 [2 3]]


In [1]:
#15
#linear algebra
import numpy as np
n=int(input())
a=np.array([input().split() for i in range(n)],float)

print(round(np.linalg.det(a)))



2
1.1 1.1
1.1 1.1
0


In [2]:
#16
#min max
import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
print(np.std(b))


2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875
